version: '2'

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - /usr/src/app/media:/usr/src/app/media:rw
      - /usr/src/app/static:/usr/src/app/static:rw
    env_file: .env
    environment:
      - VIRTUAL_HOST=seenonvhs.com,www.seenonvhs.com
      - LETSENCRYPT_HOST=seenonvhs.com,www.seenonvhs.com
      - LETSENCRYPT_EMAIL=mail@seenonvhs.com
      - LETSENCRYPT_TEST=false
    # command: ls -all
    command: /usr/src/app/startup.sh
    networks:
      - proxy
      - default

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:

networks:
  proxy:
    external:
      name: proxy
