# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_artist', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='artist-photos/')),
                ('biography', models.TextField(max_length=500, null=True)),
                ('contact_name', models.CharField(max_length=100, null=True, verbose_name='Contact / Management Name')),
                ('contact_link', models.URLField(null=True, verbose_name='Contact / Management URL')),
                ('contact_email', models.EmailField(default='info@interlinerecords.com', max_length=254, verbose_name='Contact / Management Email')),
                ('website', models.URLField(null=True)),
                ('spotify', models.URLField(null=True)),
                ('youtube', models.URLField(null=True, verbose_name='YouTube')),
                ('bandcamp', models.URLField(null=True)),
                ('itunes', models.URLField(null=True, verbose_name='iTunes')),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('soundcloud', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.Artist'),
        ),
    ]
