# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bandcamp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_link',
            field=models.URLField(default='https://www.interlinerecords.com', verbose_name='Contact / Management URL'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='contact_name',
            field=models.CharField(default='Interline Records', max_length=100, verbose_name='Contact / Management Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='itunes',
            field=models.URLField(blank=True, null=True, verbose_name='iTunes'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artist-photos/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='soundcloud',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
