# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20170316_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
