# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
