# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artist_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
