# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20170213_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bandcamp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='contact_email',
            field=models.EmailField(default='info@interlinerecords.com', max_length=254, verbose_name='Contact / Management Email'),
        ),
        migrations.AddField(
            model_name='artist',
            name='contact_link',
            field=models.URLField(blank=True, verbose_name='Contact / Management URL'),
        ),
        migrations.AddField(
            model_name='artist',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact / Management Name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='itunes',
            field=models.URLField(blank=True, verbose_name='iTunes'),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
