# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20170305_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='display_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bandcamp',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='itunes',
            field=models.URLField(blank=True, default='', verbose_name='iTunes'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True, default='', verbose_name='YouTube'),
        ),
    ]
