# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField(blank=True, max_length=300)),
                ('link', models.URLField(blank=True)),
                ('public_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=100)),
                ('site_description', models.CharField(blank=True, max_length=250)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('store', models.URLField(blank=True)),
                ('about_us', models.TextField(blank=True, max_length=600)),
                ('contact', models.TextField(blank=True, max_length=600)),
                ('contact_photo', models.ImageField(blank=True, upload_to='site-photos/', verbose_name='Conatct Photo')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=200)),
                ('background_photo_lp', models.ImageField(blank=True, upload_to='site-photos/', verbose_name='Background Photo Landing Page')),
                ('background_photo_ap', models.ImageField(blank=True, upload_to='site-photos/', verbose_name='Background Photo Artist Page')),
                ('background_photo_ad', models.ImageField(blank=True, upload_to='site-photos/', verbose_name='Background Photo Artist Detail Page')),
            ],
        ),
    ]
