# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170316_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
    ]
