# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_announcement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='public_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='display',
            field=models.BooleanField(default=False, verbose_name='DISPLAY COMPANY PUBLICLY ?'),
        ),
    ]
