# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20170316_0447'),
        ('general', '0004_auto_20170316_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='artists.Album'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='artists.Artist'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='artists.Video'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='display',
            field=models.BooleanField(default=False, verbose_name='PUBLIC ?'),
        ),
    ]
