# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20170317_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='soundcloud',
            field=models.URLField(blank=True),
        ),
    ]
