# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20170509_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='demo_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
